[package]
name = "autogen"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
env_logger = "0.11.0"
log = "0.4.20"
schemars = "0.8.16"
serde = "1.0.195"
serde_json = "1.0.111"
tailcall = { path = "../" }
tokio = { version = "1.35.1", features = ["full"] }
