[package]
name = "tailcall-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.60", features = ["derive", "full"] }
quote = "1.0.36"
proc-macro2 = "1.0.81"
