name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '0 * * * *' # This makes it run every hour

env:
  DAYS_BEFORE_ISSUE_STALE: 30
  DAYS_BEFORE_ISSUE_CLOSE: 7
  DAYS_BEFORE_PR_STALE: 2
  DAYS_BEFORE_PR_CLOSE: 5

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: |
            ðŸ“Œ This issue has been inactive for ${{ env.DAYS_BEFORE_ISSUE_STALE }} days. 
            We value your contribution!
            Please finish what you started or provide updates. 
            If no activity is seen, it will be closed in 
            ${{ env.DAYS_BEFORE_ISSUE_CLOSE }} days. ðŸ˜¢
          close-issue-message: |
            ðŸš« This issue was closed due to ${{ env.DAYS_BEFORE_ISSUE_CLOSE }} days 
            of inactivity. We encourage you to pick it up again or start a new one! ðŸš€
          stale-pr-message: |
            ðŸ“Œ This PR has been inactive for ${{ env.DAYS_BEFORE_PR_STALE }} days. 
            We value your effort! Please continue and finish your work or provide updates. 
            If no activity is seen, it will be closed in 
            ${{ env.DAYS_BEFORE_PR_CLOSE }} days. ðŸ˜¢
          close-pr-message: |
            ðŸš« This PR was closed due to ${{ env.DAYS_BEFORE_PR_CLOSE }} days 
            of inactivity. We encourage you to pick it up again or start a new one! ðŸš€
          days-before-stale: ${{ env.DAYS_BEFORE_ISSUE_STALE }}
          days-before-issue-close: ${{ env.DAYS_BEFORE_ISSUE_CLOSE }}
          days-before-pr-stale: ${{ env.DAYS_BEFORE_PR_STALE }}
          days-before-pr-close: ${{ env.DAYS_BEFORE_PR_CLOSE }}
